name: se3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  animated_theme_switcher: ^2.0.10
  awesome_dialog: ^3.2.1
  bloc: ^9.1.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_form_builder: ^10.0.1
  flutter_localizations:
    sdk: flutter
  flutter_otp_text_field: ^1.5.1+1
  flutter_secure_storage: ^9.2.4
  form_builder_validators: ^11.1.2
  get_it: ^8.2.0
  loading_indicator: ^3.1.1
  otp_text_field: ^1.1.3
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/